export const CREATE_COMMENT = 'POST/CREATE_COMMENT';
export const FETCH_COMMENTS = 'POST/FETCH_COMMENTS';
export const REQUEST_COMMENTS = 'POST/REQUEST_COMMENTS';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
